// packages/react/src/components/Toggle/Toggle.tsx
import React, { forwardRef, useId } from 'react';
import clsx from 'clsx';
import styles from './Toggle.module.css';
import { useControllableState } from '../../hooks/useControllableState';

// ─── Types ────────────────────────────────────────────────────────────────────

export type ToggleSize = 'm' | 's' | 'xs';

export interface ToggleProps {
  checked?: boolean;
  defaultChecked?: boolean;
  disabled?: boolean;
  size?: ToggleSize;
  label?: string;
  showText?: boolean;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  id?: string;
  className?: string;
  style?: React.CSSProperties;
}

// ─── Component ───────────────────────────────────────────────────────────────

export const Toggle = forwardRef<HTMLInputElement, ToggleProps>(
  (
    {
      checked,
      defaultChecked,
      disabled = false,
      size = 'm',
      label,
      showText = true,
      onChange,
      id: idProp,
      className,
      style,
    },
    ref,
  ) => {
    const autoId = useId();
    const id = idProp ?? autoId;

    const [isChecked, setChecked] = useControllableState<boolean>(checked, defaultChecked ?? false);

    // switch 상태를 내부/외부에서 동일하게 관찰할 수 있도록 동기화한다.
    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      setChecked(e.target.checked);
      onChange?.(e);
    };

    return (
      <label
        htmlFor={id}
        className={clsx(
          styles.wrapper,
          disabled && styles.disabled,
          className,
        )}
        style={style}
      >
        <input
          ref={ref}
          id={id}
          type="checkbox"
          role="switch"
          className={styles.input}
          checked={checked}
          defaultChecked={checked !== undefined ? undefined : defaultChecked}
          disabled={disabled}
          onChange={handleChange}
          aria-checked={isChecked}
        />
        <span
          className={clsx(
            styles.track,
            styles[size],
            isChecked ? styles.on : styles.off,
            disabled && styles.trackDisabled,
            !showText && styles.noText,
          )}
        >
          {showText && <span className={styles.onText}>ON</span>}
          <span className={styles.knob} />
          {showText && <span className={styles.offText}>OFF</span>}
        </span>
        {label && <span className={styles.label}>{label}</span>}
      </label>
    );
  },
);

Toggle.displayName = 'Toggle';

// packages/vue/src/components/Toggle/Toggle.vue
<script setup lang="ts">
import { computed, useId } from 'vue';
import { useControllableState } from '../../composables/useControllableState';

export type ToggleSize = 'm' | 's' | 'xs';

const props = withDefaults(
  defineProps<{
    modelValue?: boolean;
    defaultChecked?: boolean;
    disabled?: boolean;
    size?: ToggleSize;
    label?: string;
    showText?: boolean;
    id?: string;
  }>(),
  {
    disabled: false,
    size: 'm',
    showText: true,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  change: [value: boolean];
}>();

const autoId = useId();
const id = computed(() => props.id ?? autoId);

const { value: isChecked, setValue } = useControllableState(
  () => props.modelValue,
  props.defaultChecked ?? false,
  (v) => {
    emit('update:modelValue', v);
    emit('change', v);
  },
);

function handleChange(e: Event) {
  setValue((e.target as HTMLInputElement).checked);
}
</script>

<template>
  <label
    :for="id"
    :class="[$style.wrapper, disabled && $style.disabled]"
  >
    <input
      :id="id"
      type="checkbox"
      role="switch"
      :class="$style.input"
      :checked="isChecked"
      :disabled="disabled"
      :aria-checked="isChecked"
      @change="handleChange"
    />
    <span
      :class="[
        $style.track,
        $style[size],
        isChecked ? $style.on : $style.off,
        disabled && $style.trackDisabled,
        !showText && $style.noText,
      ]"
    >
      <span v-if="showText" :class="$style.onText">ON</span>
      <span :class="$style.knob" />
      <span v-if="showText" :class="$style.offText">OFF</span>
    </span>
    <span v-if="label" :class="$style.label">{{ label }}</span>
  </label>
</template>

<style module src="./Toggle.module.css"></style>
