// packages/react/src/components/Button/Button.tsx
import { forwardRef, type ButtonHTMLAttributes, type ReactNode } from 'react';
import clsx from 'clsx';
import styles from './Button.module.css';

export type ButtonVariant =
  // Primary (red)
  | 'primary'          // P1 — solid filled
  | 'primary-outline'  // P2 — outline
  | 'primary-surface'  // P3 — white bg + shadow
  | 'primary-ghost'    // P4 — text only
  // Secondary (gray)
  | 'secondary'        // S1 — outline
  | 'secondary-surface'// S2 — white bg + shadow
  | 'secondary-ghost'  // S3 — text only
  // Action (green)
  | 'action'           // A1 — outline
  | 'action-surface'   // A2 — white bg + shadow
  | 'action-ghost'     // A3 — text only
  // Accent (blue)
  | 'accent'           // Ac1 — outline
  | 'accent-surface'   // Ac2 — white bg + shadow
  | 'accent-ghost';    // Ac3 — text only

export type ButtonSize = 'xs' | 's' | 'm' | 'l';
export type ButtonShape = 'pill' | 'rounded';

export interface ButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  /** 버튼 색상 및 스타일 변형 */
  variant?: ButtonVariant;
  /** 버튼 높이 크기 */
  size?: ButtonSize;
  /** 버튼 모서리 형태 */
  shape?: ButtonShape;
  /** 버튼 좌측 아이콘 */
  leftIcon?: ReactNode;
  /** 버튼 우측 아이콘 */
  rightIcon?: ReactNode;
  /** 로딩 스피너 표시 (클릭 비활성화) */
  loading?: boolean;
  /** 너비 100% 확장 */
  fullWidth?: boolean;
  /** 버튼 텍스트 */
  children?: ReactNode;
}

const variantClass: Record<ButtonVariant, string> = {
  'primary':          styles.primary,
  'primary-outline':  styles.primaryOutline,
  'primary-surface':  styles.primarySurface,
  'primary-ghost':    styles.primaryGhost,
  'secondary':        styles.secondary,
  'secondary-surface':styles.secondarySurface,
  'secondary-ghost':  styles.secondaryGhost,
  'action':           styles.action,
  'action-surface':   styles.actionSurface,
  'action-ghost':     styles.actionGhost,
  'accent':           styles.accent,
  'accent-surface':   styles.accentSurface,
  'accent-ghost':     styles.accentGhost,
};

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      variant = 'primary',
      size = 'm',
      shape = 'pill',
      leftIcon,
      rightIcon,
      loading = false,
      fullWidth = false,
      disabled = false,
      children,
      className,
      ...rest
    },
    ref,
  ) => {
    const iconOnly = !children;

    return (
      <button
        ref={ref}
        type="button"
        disabled={disabled || loading}
        aria-busy={loading || undefined}
        className={clsx(
          styles.btn,
          styles[size],
          styles[shape],
          variantClass[variant],
          leftIcon && styles.hasLeft,
          rightIcon && styles.hasRight,
          iconOnly && styles.iconOnly,
          fullWidth && styles.fullWidth,
          loading && styles.loading,
          className,
        )}
        {...rest}
      >
        {loading ? (
          <svg
            className={styles.spinner}
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 26 26"
            fill="none"
            aria-hidden="true"
          >
            <path
              d="M22.3601 12.9996C22.3601 12.0975 22.2325 11.2251 21.9943 10.3996C20.8676 6.4952 17.2674 3.63965 13.0001 3.63965C7.83075 3.63965 3.64014 7.83026 3.64014 12.9996C3.64014 18.169 7.83075 22.3596 13.0001 22.3596C13.8081 22.3596 14.5922 22.2573 15.3401 22.0648"
              stroke="currentColor"
              strokeWidth="3.64"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        ) : (
          <>
            {leftIcon && <span className={styles.icon}>{leftIcon}</span>}
            {children}
            {rightIcon && <span className={styles.icon}>{rightIcon}</span>}
          </>
        )}
      </button>
    );
  },
);

Button.displayName = 'Button';

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed, useAttrs, useCssModule, type VNode } from 'vue';

export type ButtonVariant =
  | 'primary'
  | 'primary-outline'
  | 'primary-surface'
  | 'primary-ghost'
  | 'secondary'
  | 'secondary-surface'
  | 'secondary-ghost'
  | 'action'
  | 'action-surface'
  | 'action-ghost'
  | 'accent'
  | 'accent-surface'
  | 'accent-ghost';

export type ButtonSize = 'xs' | 's' | 'm' | 'l';
export type ButtonShape = 'pill' | 'rounded';

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant;
    size?: ButtonSize;
    shape?: ButtonShape;
    loading?: boolean;
    fullWidth?: boolean;
    disabled?: boolean;
  }>(),
  {
    variant: 'primary',
    size: 'm',
    shape: 'pill',
    loading: false,
    fullWidth: false,
    disabled: false,
  },
);

defineOptions({ inheritAttrs: false });

const attrs = useAttrs();
const styles = useCssModule();

const VARIANT_CLASS: Record<ButtonVariant, string> = {
  'primary':           'primary',
  'primary-outline':   'primaryOutline',
  'primary-surface':   'primarySurface',
  'primary-ghost':     'primaryGhost',
  'secondary':         'secondary',
  'secondary-surface': 'secondarySurface',
  'secondary-ghost':   'secondaryGhost',
  'action':            'action',
  'action-surface':    'actionSurface',
  'action-ghost':      'actionGhost',
  'accent':            'accent',
  'accent-surface':    'accentSurface',
  'accent-ghost':      'accentGhost',
};

const hasLeft = computed(() => {
  const content = slots.leftIcon?.() as VNode[] | undefined;
  return !!content && content.length > 0;
});
const hasRight = computed(() => {
  const content = slots.rightIcon?.() as VNode[] | undefined;
  return !!content && content.length > 0;
});
const iconOnly = computed(() => {
  const content = slots.default?.() as VNode[] | undefined;
  return !content || content.length === 0;
});

const buttonClass = computed(() => [
  styles.btn,
  styles[props.size],
  styles[props.shape],
  styles[VARIANT_CLASS[props.variant!]],
  hasLeft.value && styles.hasLeft,
  hasRight.value && styles.hasRight,
  iconOnly.value && styles.iconOnly,
  props.fullWidth && styles.fullWidth,
  props.loading && styles.loading,
]);

const slots = defineSlots<{
  default?: () => unknown;
  leftIcon?: () => unknown;
  rightIcon?: () => unknown;
}>();
</script>

<template>
  <button
    type="button"
    v-bind="attrs"
    :disabled="disabled || loading"
    :aria-busy="loading || undefined"
    :class="buttonClass"
  >
    <template v-if="loading">
      <svg
        :class="$style.spinner"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 26 26"
        fill="none"
        aria-hidden="true"
      >
        <path
          d="M22.3601 12.9996C22.3601 12.0975 22.2325 11.2251 21.9943 10.3996C20.8676 6.4952 17.2674 3.63965 13.0001 3.63965C7.83075 3.63965 3.64014 7.83026 3.64014 12.9996C3.64014 18.169 7.83075 22.3596 13.0001 22.3596C13.8081 22.3596 14.5922 22.2573 15.3401 22.0648"
          stroke="currentColor"
          stroke-width="3.64"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </template>
    <template v-else>
      <span v-if="hasLeft" :class="$style.icon"><slot name="leftIcon" /></span>
      <slot />
      <span v-if="hasRight" :class="$style.icon"><slot name="rightIcon" /></span>
    </template>
  </button>
</template>

<style module src="./Button.module.css"></style>
