// packages/react/src/components/Tabs/TabPill.tsx
import React, { forwardRef } from 'react';
import clsx from 'clsx';
import styles from './TabPill.module.css';
import { useControllableState } from '../../hooks/useControllableState';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface TabPillItem {
  label: string;
  value: string;
  icon?: React.ReactNode;
  disabled?: boolean;
}

export interface TabPillProps {
  items: TabPillItem[];
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: React.CSSProperties;
}

// ─── Component ───────────────────────────────────────────────────────────────

export const TabPill = forwardRef<HTMLDivElement, TabPillProps>(
  (
    {
      items,
      value,
      defaultValue,
      onChange,
      className,
      style,
    },
    ref,
  ) => {
    const [currentValue, setCurrentValue] = useControllableState(
      value,
      defaultValue ?? items[0]?.value,
      onChange,
    );
    const hasIcons = items.some((item) => item.icon);

    // pill 탭 선택 로직을 단일 함수로 모아 controlled/uncontrolled 흐름을 유지한다.
    const handleSelect = (itemValue: string) => setCurrentValue(itemValue);

    return (
      <div
        ref={ref}
        className={clsx(styles.wrapper, className)}
        style={style}
        role="tablist"
      >
        {items.map((item) => {
          const isSelected = currentValue === item.value;

          return (
            <button
              key={item.value}
              type="button"
              role="tab"
              aria-selected={isSelected}
              className={clsx(
                styles.item,
                isSelected && styles.selected,
                hasIcons ? styles.withIcon : styles.textOnly,
                item.disabled && styles.itemDisabled,
              )}
              onClick={() => !item.disabled && handleSelect(item.value)}
              disabled={item.disabled}
            >
              {item.icon && (
                <span className={clsx(styles.icon, item.disabled && styles.iconDisabled)}>
                  {item.icon}
                </span>
              )}
              <span className={styles.label}>{item.label}</span>
            </button>
          );
        })}
      </div>
    );
  },
);

TabPill.displayName = 'TabPill';

// packages/vue/src/components/Tabs/TabPill.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useControllableState } from '../../composables/useControllableState';

export interface TabPillItem {
  label: string;
  value: string;
  icon?: unknown;
  disabled?: boolean;
}

const props = defineProps<{
  items: TabPillItem[];
  modelValue?: string;
  defaultValue?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: string];
  change: [value: string];
}>();

const { value: currentValue, setValue } = useControllableState(
  () => props.modelValue,
  props.defaultValue ?? props.items[0]?.value ?? '',
  (value) => {
    emit('update:modelValue', value);
    emit('change', value);
  },
);

const hasIcons = computed(() => props.items.some((item) => !!item.icon));

function handleSelect(itemValue: string) {
  setValue(itemValue);
}
</script>

<template>
  <div :class="$style.wrapper" role="tablist">
    <button
      v-for="item in items"
      :key="item.value"
      type="button"
      role="tab"
      :aria-selected="currentValue === item.value"
      :class="[
        $style.item,
        currentValue === item.value && $style.selected,
        hasIcons ? $style.withIcon : $style.textOnly,
        item.disabled && $style.itemDisabled,
      ]"
      :disabled="item.disabled"
      @click="!item.disabled && handleSelect(item.value)"
    >
      <span v-if="item.icon" :class="[$style.icon, item.disabled && $style.iconDisabled]">
        <component :is="item.icon" />
      </span>
      <span :class="$style.label">{{ item.label }}</span>
    </button>
  </div>
</template>

<style module src="./TabPill.module.css"></style>
