// packages/react/src/components/Modal/ModalBody.tsx
import React, { forwardRef, useEffect, useRef, useState } from 'react';
import clsx from 'clsx';
import styles from './Modal.module.css';

export interface ModalBodyProps {
  children?: React.ReactNode;
  /** 스크롤 시 상하단 fadeout 그라디언트 적용 */
  fadeout?: boolean;
  className?: string;
}

export const ModalBody = forwardRef<HTMLDivElement, ModalBodyProps>(
  ({ children, className, fadeout = false }, ref) => {
    const bodyRef = useRef<HTMLDivElement>(null);
    const [showTop, setShowTop] = useState(false);
    const [showBottom, setShowBottom] = useState(false);

    useEffect(() => {
      if (!fadeout) return;
      const el = bodyRef.current;
      if (!el) return;

      // 현재 스크롤 위치를 기준으로 상단/하단 페이드 표시 여부를 갱신한다.
      const check = () => {
        setShowTop(el.scrollTop > 0);
        setShowBottom(Math.ceil(el.scrollTop) + el.clientHeight < el.scrollHeight);
      };

      check();
      el.addEventListener('scroll', check, { passive: true });
      const ro = new ResizeObserver(check);
      ro.observe(el);

      return () => {
        el.removeEventListener('scroll', check);
        ro.disconnect();
      };
    }, [fadeout]);

    if (!fadeout) {
      return <div ref={ref} className={clsx(styles.body, className)}>{children}</div>;
    }

    return (
      <div ref={ref} className={clsx(styles.bodyOuter, className)}>
        <div className={clsx(styles.body, styles.bodyScrollable)} ref={bodyRef}>
          {children}
        </div>
        <div className={clsx(styles.fadeTop, showTop && styles.fadeVisible)} />
        <div className={clsx(styles.fadeBottom, showBottom && styles.fadeVisible)} />
      </div>
    );
  },
);

ModalBody.displayName = 'ModalBody';

// packages/vue/src/components/Modal/ModalBody.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';

const props = withDefaults(
  defineProps<{
    fadeout?: boolean;
  }>(),
  {
    fadeout: false,
  },
);

const bodyRef = ref<HTMLDivElement | null>(null);
const showTop = ref(false);
const showBottom = ref(false);

let resizeObserver: ResizeObserver | null = null;

function updateFadeState() {
  const el = bodyRef.value;
  if (!el) return;
  showTop.value = el.scrollTop > 0;
  showBottom.value = Math.ceil(el.scrollTop) + el.clientHeight < el.scrollHeight;
}

function bindScrollable() {
  if (!props.fadeout) return;
  const el = bodyRef.value;
  if (!el) return;
  updateFadeState();
  el.addEventListener('scroll', updateFadeState, { passive: true });
  resizeObserver = new ResizeObserver(updateFadeState);
  resizeObserver.observe(el);
}

function unbindScrollable() {
  const el = bodyRef.value;
  if (el) {
    el.removeEventListener('scroll', updateFadeState);
  }
  resizeObserver?.disconnect();
  resizeObserver = null;
}

onMounted(async () => {
  if (!props.fadeout) return;
  await nextTick();
  bindScrollable();
});

watch(
  () => props.fadeout,
  async (enabled) => {
    unbindScrollable();
    if (enabled) {
      await nextTick();
      bindScrollable();
    }
  },
);

onBeforeUnmount(() => {
  unbindScrollable();
});
</script>

<template>
  <div v-if="!fadeout" :class="$style.body">
    <slot />
  </div>
  <div v-else :class="$style.bodyOuter">
    <div ref="bodyRef" :class="[$style.body, $style.bodyScrollable]">
      <slot />
    </div>
    <div :class="[$style.fadeTop, showTop && $style.fadeVisible]" />
    <div :class="[$style.fadeBottom, showBottom && $style.fadeVisible]" />
  </div>
</template>

<style module src="./Modal.module.css"></style>
